  
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: dateapi-destinationrule
spec:
  host: dateapi
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
  trafficPolicy:
    outlierDetection:
      consecutiveErrors: 1
      interval: 10s
      baseEjectionTime: 3m
      maxEjectionPercent: 100
