apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasksapp
  labels:
    app: tasksapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasksapp
  template:
    metadata:
      labels:
        app: tasksapp
    spec:
      containers:
        - name: tasksapp
          image: getmub/myapi
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: dateapi-configmap
                  key: MONGO_HOST
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: dateapi-configmap
                  key: MONGO_PORT
          imagePullPolicy: Always
