apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: foo-circuitbreaker
spec:
  host: foo
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 1
        maxRequestsPerConnection: 1
    outlierDetection:
      consecutiveErrors: 1
      interval: 10s
      baseEjectionTime: 3m
      maxEjectionPercent: 100
