apiVersion: networking.k8s.io/v1beta1 
 kind: Ingress
 metadata:
   name: myingress
   annotations:
     nginx.ingress.kubernetes.io/rewrite-target: /$1
 spec:
   rules:
   - host: myhost
     http:
       paths:
       - path: /date
         backend:
           serviceName: dateapi
           servicePort: 8080
