apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dateapi-virtual-service
spec:
  hosts:
    - dateapi        
  http:
  - route:
    - destination:
        host: dateapi 
        subset: v1      
    mirror:             
      host: dateapi    
      subset: v2
